In [24]:
import pandas as pd
# joining 2018 areas results to 2018 population results to get the extra census tracts and set those to 0
df2010_pop = pd.read_csv(r"t:\60day-TEMP\Brice\hct_population_coverage_2018.csv", dtype={"GEOID": str})
df2010_area = pd.read_csv(r"t:\60day-TEMP\Brice\hct_area_coverage_2018.csv", dtype={"GEOID": str})
df2010_pop.columns
df2010_area_all_tracts = df2010_pop.merge(df2010_area, on="geoid10", how="left")
len(df2010_area_all_tracts)
# df2010_area_all_tracts[["geoid10", "quarter_mile_hct_sq_ft", "total_area", "percent_hct"]].fillna(0)
# df2010_area_all_tracts["population"] = df2010_area_all_tracts["population"].fillna(0)

776

In [30]:
len(df2010_pop)

776

In [31]:
len(df2010_area)

212

In [32]:
df2010_area_all_tracts = df2010_area_all_tracts[["geoid10", "quarter_mile_hct_sq_ft", "total_area", "percent_hct"]].fillna(0)
len(df2010_area_all_tracts)
df2010_area_all_tracts

         geoid10  quarter_mile_hct_sq_ft  total_area  percent_hct
0    53033022006                     0.0         0.0          0.0
1    53033032320                     0.0         0.0          0.0
2    53033031703                     0.0         0.0          0.0
3    53033031206                     0.0         0.0          0.0
4    53033032102                     0.0         0.0          0.0
..           ...                     ...         ...          ...
771  53061052112                     0.0         0.0          0.0
772  53061052113                     0.0         0.0          0.0
773  53061052402                     0.0         0.0          0.0
774  53061052805                     0.0         0.0          0.0
775  53061041808                     0.0         0.0          0.0

[776 rows x 4 columns]

In [28]:
df2010_area_all_tracts["geoid10"] == "53033000601"
df2010_area_all_tracts[df2010_area_all_tracts["geoid10"] == 53033000601]

Empty DataFrame
Columns: [geoid10, quarter_mile_hct_sq_ft, total_area, percent_hct]
Index: []

In [44]:
import pandas as pd

df2020 = pd.read_csv(r"C:\workspace\displacement_index\displacement_index_current\09-Proximity-to-Current-or-Future-HCT\Output\hct_area_coverage_2023.csv", dtype={"GEOID": str})
crosswalk = pd.read_csv(r"c:\workspace\displacement_index\displacement_index_current\nhgis_tr2010_tr2020_53.csv",
                        dtype={"GEOID_2010": str, "GEOID_2020": str})
# crosswalk.groupby("tr2010ge")["wt_pop"].sum().describe()
df2020.columns
# crosswalk.columns

Index(['geoid20', 'total_area', 'quarter_mile_hct_sq_ft', 'percent_hct'], dtype='object')

In [46]:
crosswalk[crosswalk["tr2020ge"] == 53033000601]

,tr2010gj,tr2010ge,tr2020gj,tr2020ge,parea,wt_pop,wt_adult,wt_fam,wt_hh,wt_hu,wt_ownhu,wt_renthu
728,G5300330000600,53033000600,G5300330000601,53033000601,0.377139,0.502885,0.50738,0.498869,0.505531,0.51498,0.48538,0.531421
730,G5300330000700,53033000700,G5300330000601,53033000601,0.000185,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000
738,G5300330001200,53033001200,G5300330000601,53033000601,0.002399,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000

In [47]:
merged = df2010_area_all_tracts.merge(
    crosswalk,
    left_on="geoid10",
    right_on="tr2010ge",
    how="left"
)
merged

,geoid10,quarter_mile_hct_sq_ft,total_area,percent_hct,tr2010gj,tr2010ge,tr2020gj,tr2020ge,parea,wt_pop,wt_adult,wt_fam,wt_hh,wt_hu,wt_ownhu,wt_renthu
0,53033022006,0.0,0.0,0.0,G5300330022006,53033022006,G5300330022006,53033022006,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,53033032320,0.0,0.0,0.0,G5300330032320,53033032320,G5300330032307,53033032307,0.009535,0.004756,0.004195,0.004153,0.003506,0.003392,0.003084,0.007752
2,53033032320,0.0,0.0,0.0,G5300330032320,53033032320,G5300330032319,53033032319,0.000174,0.000400,0.000399,0.000496,0.000460,0.000445,0.000473,0.000321
3,53033032320,0.0,0.0,0.0,G5300330032320,53033032320,G5300330032320,53033032320,0.985818,0.993241,0.993588,0.993361,0.994170,0.994342,0.994433,0.991518
4,53033032320,0.0,0.0,0.0,G5300330032320,53033032320,G5300330032321,53033032321,0.004473,0.001603,0.001818,0.001990,0.001865,0.001822,0.002009,0.000408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,53061052402,0.0,0.0,0.0,G5300610052402,53061052402,G5300610052402,53061052402,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1489,53061052805,0.0,0.0,0.0,G5300610052805,53061052805,G5300610052805,53061052805,0.947264,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1490,53061052805,0.0,0.0,0.0,G5300610052805,53061052805,G5300610052905,53061052905,0.000477,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1491,53061052805,0.0,0.0,0.0,G5300610052805,53061052805,G5300610940001,53061940001,0.052259,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1492,53061041808,0.0,0.0,0.0,G5300610041808,53061041808,G5300610041808,53061041808,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [48]:
merged_parea = merged[merged["parea"] == 1]
merged_parea

,geoid10,quarter_mile_hct_sq_ft,total_area,percent_hct,tr2010gj,tr2010ge,tr2020gj,tr2020ge,parea,wt_pop,wt_adult,wt_fam,wt_hh,wt_hu,wt_ownhu,wt_renthu
0,53033022006,0.000000,0.000000e+00,0.0000,G5300330022006,53033022006,G5300330022006,53033022006,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
15,53033032211,0.000000,0.000000e+00,0.0000,G5300330032211,53033032211,G5300330032211,53033032211,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
33,53033027300,0.000000,0.000000e+00,0.0000,G5300330027300,53033027300,G5300330027300,53033027300,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
39,53033027000,0.000000,0.000000e+00,0.0000,G5300330027000,53033027000,G5300330027000,53033027000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
40,53033026802,0.000000,0.000000e+00,0.0000,G5300330026802,53033026802,G5300330026802,53033026802,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1479,53061050102,870781.137165,1.943722e+07,0.0448,G5300610050102,53061050102,G5300610050102,53061050102,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1483,53061051918,0.000000,0.000000e+00,0.0000,G5300610051918,53061051918,G5300610051918,53061051918,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1486,53061052113,0.000000,0.000000e+00,0.0000,G5300610052113,53061052113,G5300610052113,53061052113,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1488,53061052402,0.000000,0.000000e+00,0.0000,G5300610052402,53061052402,G5300610052402,53061052402,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1492,53061041808,0.000000,0.000000e+00,0.0000,G5300610041808,53061041808,G5300610041808,53061041808,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [ ]:
# merged["area2010_weighted"] = merged["total_area"] * merged["parea"]
# merged["area2010_weighted"]
# merged

,geoid10,quarter_mile_hct_sq_ft,total_area,percent_hct,tr2010gj,tr2010ge,tr2020gj,tr2020ge,parea,wt_pop,wt_adult,wt_fam,wt_hh,wt_hu,wt_ownhu,wt_renthu,area2010_weighted
0,53033000100,0.0,0.0,0.0,G5300330000100,53033000100,G5300330000101,53033000101,0.217172,0.435811,0.415644,0.428793,0.432295,0.434505,0.169663,0.535904,0.0
1,53033000100,0.0,0.0,0.0,G5300330000100,53033000100,G5300330000102,53033000102,0.782639,0.564189,0.584356,0.571207,0.567705,0.565495,0.830337,0.464096,0.0
2,53033000100,0.0,0.0,0.0,G5300330000100,53033000100,G5300330000800,53033000800,0.000190,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,53033000200,0.0,0.0,0.0,G5300330000200,53033000200,G5300330000201,53033000201,0.549616,0.492807,0.511534,0.466852,0.556730,0.555976,0.455959,0.680688,0.0
4,53033000200,0.0,0.0,0.0,G5300330000200,53033000200,G5300330000202,53033000202,0.450384,0.507193,0.488466,0.533148,0.443270,0.444024,0.544041,0.319312,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,53061940001,0.0,0.0,0.0,G5300610940001,53061940001,G5300610052903,53061052903,0.000012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1489,53061940001,0.0,0.0,0.0,G5300610940001,53061940001,G5300610940001,53061940001,0.999988,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0
1490,53061940002,0.0,0.0,0.0,G5300610940002,53061940002,G5300610940002,53061940002,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0
1491,53061990002,0.0,0.0,0.0,G5300610990002,53061990002,G5300610990002,53061990002,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0
1492,53061990100,0.0,0.0,0.0,G5300610990100,53061990100,G5300610990100,53061990100,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [ ]:
# merged["area2010_quarter_mile_weighted"] = merged["quarter_mile_hct_sq_ft"] * merged["parea"]
# merged.columns

Index(['geoid10', 'quarter_mile_hct_sq_ft', 'total_area', 'percent_hct',
       'tr2010gj', 'tr2010ge', 'tr2020gj', 'tr2020ge', 'parea', 'wt_pop',
       'wt_adult', 'wt_fam', 'wt_hh', 'wt_hu', 'wt_ownhu', 'wt_renthu',
       'area2010_weighted', 'area2010_quarter_mile_weighted'],
      dtype='object')

In [49]:
df2010_adjusted = (
    merged_parea
    .groupby("tr2020ge", as_index=False)
    # [["area2010_weighted", "area2010_quarter_mile_weighted"]]
    .sum()
)
df2010_adjusted.head()

,tr2020ge,geoid10,quarter_mile_hct_sq_ft,total_area,percent_hct,tr2010gj,tr2010ge,tr2020gj,parea,wt_pop,wt_adult,wt_fam,wt_hh,wt_hu,wt_ownhu,wt_renthu
0,53033000300,53033000300,2.213854e+06,1.302888e+07,0.169919,G5300330000300,53033000300,G5300330000300,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,53033000402,53033000402,6.696492e+06,1.936218e+07,0.345854,G5300330000402,53033000402,G5300330000402,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,53033000800,53033000800,0.000000e+00,0.000000e+00,0.000000,G5300330000800,53033000800,G5300330000800,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,53033001100,53033001100,0.000000e+00,0.000000e+00,0.000000,G5300330001100,53033001100,G5300330001100,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,53033001701,53033001701,7.676939e+03,9.609056e+06,0.000799,G5300330001701,53033001701,G5300330001701,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [50]:
final = df2010_adjusted.merge(
    df2020,
    left_on="tr2020ge",
    right_on="geoid20",
    how="inner"
)

In [51]:
final.head()

,tr2020ge,geoid10,quarter_mile_hct_sq_ft_x,total_area_x,percent_hct_x,tr2010gj,tr2010ge,tr2020gj,parea,wt_pop,wt_adult,wt_fam,wt_hh,wt_hu,wt_ownhu,wt_renthu,geoid20,total_area_y,quarter_mile_hct_sq_ft_y,percent_hct_y
0,53033000300,53033000300,2.213854e+06,1.302888e+07,0.169919,G5300330000300,53033000300,G5300330000300,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53033000300,1.303428e+07,2.219193e+06,0.170258
1,53033000402,53033000402,6.696492e+06,1.936218e+07,0.345854,G5300330000402,53033000402,G5300330000402,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53033000402,1.936223e+07,6.696508e+06,0.345854
2,53033000800,53033000800,0.000000e+00,0.000000e+00,0.000000,G5300330000800,53033000800,G5300330000800,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53033000800,1.229081e+07,0.000000e+00,0.000000
3,53033001100,53033001100,0.000000e+00,0.000000e+00,0.000000,G5300330001100,53033001100,G5300330001100,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53033001100,1.141640e+07,0.000000e+00,0.000000
4,53033001701,53033001701,7.676939e+03,9.609056e+06,0.000799,G5300330001701,53033001701,G5300330001701,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53033001701,9.609031e+06,7.676917e+03,0.000799

In [19]:
final["area2010_percent_quarter_mile_weighted"] = final["area2010_quarter_mile_weighted"] / final["area2010_weighted"]
final.head()

,tr2020ge,area2010_weighted,area2010_quarter_mile_weighted,geoid20,total_area,quarter_mile_hct_sq_ft,percent_hct,area2010_percent_quarter_mile_weighted
0,53033000101,0.000000e+00,0.000000e+00,53033000101,4.465063e+06,0.000000e+00,0.000000,NaN
1,53033000102,0.000000e+00,0.000000e+00,53033000102,1.591965e+07,0.000000e+00,0.000000,NaN
2,53033000201,6.093472e+03,1.335366e+03,53033000201,1.944626e+07,0.000000e+00,0.000000,0.219147
3,53033000202,0.000000e+00,0.000000e+00,53033000202,1.593036e+07,0.000000e+00,0.000000,NaN
4,53033000300,1.302888e+07,2.213854e+06,53033000300,1.303428e+07,2.219193e+06,0.170258,0.169919

In [53]:
final.to_csv(r"C:\workspace\displacement_index\displacement_index_current\09-Proximity-to-Current-or-Future-HCT\Output\hct_area_coverage_comparison_2010_2020_parea.csv", index=False)